name: deploy-pypi
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#permissions:
#  contents: write
jobs:
  deploy-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python 3.10.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10.x

      - name: Deploy
        run: |
          echo "Install Twine"
          pip install twine

          echo "Build"
          python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
